name: flutter_talk
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.7
  cloud_firestore: ^4.15.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  uuid: ^4.3.3
  cloud_firestore_odm: ^1.0.0-dev.84

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
flutter:
  uses-material-design: true
