// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZbyEiY4iUOqhM9Q7b9cIT5Gt9SOzR9Gk',
    appId: '1:74275124142:web:45fb157e156803ef7a0e3f',
    messagingSenderId: '74275124142',
    projectId: 'flutter-talk1',
    authDomain: 'flutter-talk1.firebaseapp.com',
    storageBucket: 'flutter-talk1.appspot.com',
    measurementId: 'G-HL9JCDL75N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqPG1nF95wsNDog2gWvP5JPYxq2TpH8wA',
    appId: '1:74275124142:android:2a28ad05839c2d5d7a0e3f',
    messagingSenderId: '74275124142',
    projectId: 'flutter-talk1',
    storageBucket: 'flutter-talk1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBprKG2H5WuevNPaQeumv_QhAdzgtCsXBQ',
    appId: '1:74275124142:ios:f5e3ac8bd363593d7a0e3f',
    messagingSenderId: '74275124142',
    projectId: 'flutter-talk1',
    storageBucket: 'flutter-talk1.appspot.com',
    iosBundleId: 'com.example.flutterTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBprKG2H5WuevNPaQeumv_QhAdzgtCsXBQ',
    appId: '1:74275124142:ios:133b5d8ca499ead67a0e3f',
    messagingSenderId: '74275124142',
    projectId: 'flutter-talk1',
    storageBucket: 'flutter-talk1.appspot.com',
    iosBundleId: 'com.example.flutterTalk.RunnerTests',
  );
}
